"""Format strategy results as Telegram/Discord signal messages."""
from __future__ import annotations
from typing import Any, Dict, Optional


def format_signal(
    spec: Dict[str, Any],
    metrics: Dict[str, Any],
    grade: str = "",
    report_url: Optional[str] = None,
) -> str:
    """Format a strategy as a shareable signal message."""
    name = spec.get("name", "StratForge Strategy")
    market = spec.get("market", "crypto").upper()

    lines = [
        f"🤖 **StratForge AI Signal**",
        f"━━━━━━━━━━━━━━━━━━━━",
        f"📊 **{name}**",
        f"🏪 Market: {market}",
    ]

    if grade:
        lines.append(f"🏆 Grade: **{grade}**")

    lines.append("")
    lines.append("📈 **Performance Metrics**")

    m = metrics
    if m.get("sharpe") is not None:
        lines.append(f"  • Sharpe: {float(m['sharpe']):.2f}")
    if m.get("profit_factor") is not None:
        lines.append(f"  • Profit Factor: {float(m['profit_factor']):.2f}")
    if m.get("win_rate") is not None:
        lines.append(f"  • Win Rate: {float(m['win_rate']):.1%}")
    if m.get("max_drawdown") is not None:
        lines.append(f"  • Max Drawdown: {float(m['max_drawdown']):.1%}")
    if m.get("total_return") is not None:
        lines.append(f"  • Total Return: {float(m['total_return']):.1%}")
    if m.get("num_trades") is not None:
        lines.append(f"  • Trades: {m['num_trades']}")

    # Entry/exit summary
    entries = spec.get("entries", {})
    exits = spec.get("exits", {})
    entry_inds = _summarize_conditions(entries)
    exit_inds = _summarize_conditions(exits)

    if entry_inds:
        lines.append("")
        lines.append(f"🟢 **Entry**: {entry_inds}")
    if exit_inds:
        lines.append(f"🔴 **Exit**: {exit_inds}")

    # Stops
    stops = spec.get("stops", {})
    sl = stops.get("stop_loss", {})
    tp = stops.get("take_profit", {})
    if sl:
        if sl.get("type") == "fixed_pct":
            lines.append(f"🛡️ **Stop Loss**: {float(sl.get('value', 0)):.1%}")
        elif sl.get("type") == "atr":
            lines.append(f"🛡️ **Stop Loss**: {sl.get('multiplier', 2.0)}x ATR({sl.get('period', 14)})")
    if tp:
        if tp.get("type") == "fixed_pct":
            lines.append(f"🎯 **Take Profit**: {float(tp.get('value', 0)):.1%}")

    if report_url:
        lines.append("")
        lines.append(f"📄 [Full Report]({report_url})")

    lines.append("")
    lines.append("⚠️ *Not financial advice. Past performance ≠ future results.*")
    lines.append("_Generated by StratForge AI_")

    return "\n".join(lines)


def _summarize_conditions(group: Dict) -> str:
    parts = []
    for key in ("all_of", "any_of"):
        for cond in group.get(key, []):
            if "indicator" in cond:
                ind = cond["indicator"].upper()
                op = cond.get("op", "")
                val = cond.get("value", cond.get("ref", ""))
                parts.append(f"{ind} {op} {val}")
    joiner = " AND " if group.get("all_of") else " OR "
    return joiner.join(parts) if parts else ""
